all:
  children:
    wsl:
      hosts:
        localhost:
        #ridesktop:
        #chopin:
    server:
      hosts:
        microserver.rigarash.info:
    ricos:
      hosts:
        savanna.ritc.jp:
        #jungle.ritc.jp:
    supercomputer:
      hosts:
        reedbush.cc.u-tokyo.ac.jp:
    cluster:
      children:
        ricos:
        supercomputer:
    windows:
      hosts:
        local_windows:
      vars:
        ansible_host: localhost
        ansible_user: rigarash
        ansible_connection: winrm
        ansible_winrm_transport: credssp
