all:
  children:
    wsl:
      hosts:
        localhost:
        #ridesktop:
        #chopin:
    server:
      hosts:
        microserver.rigarash.info:
    ricos:
      hosts:
        ln.savanna.ritc.jp:
      vars:
        ansible_python_interpreter: /usr/bin/python3
    supercomputer:
      hosts:
        #reedbush.cc.u-tokyo.ac.jp:
        abci.ai:
        squidhpc.hpc.cmc.osaka-u.ac.jp:
    cluster:
      children:
        ricos:
        supercomputer:
    windows:
      hosts:
        local_windows:
      vars:
        ansible_host: localhost
        ansible_user: rigarash
        ansible_connection: winrm
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
