---
# This playbook deploys the whole application stack in this site for now.

- name: common settings for all sites
  hosts: localhost

  roles:
    - { role: apt,         become: true }
    - common
    - { role: programming, become: true }
