---
# This playbook deploys the whole application stack in this site for now.

- name: common settings for wsl sites
  hosts: localhost
  connection: local
  pre_tasks:
    - include:
        pre_tasks/version_check.yml
  roles:
    - apt
    - common
    - wsl
    - programming
    - texlive

- name: common settings for managed servers
  hosts: server
  gather_facts: False
  pre_tasks:
    - include:
        pre_tasks/version_check.yml
    - name: Collect facts except Ohai
      setup:
        gather_subset: "!ohai"
  roles:
    - apt
    - common

- name: common settings for clusters
  hosts: cluster
  gather_facts: False
  pre_tasks:
    - include:
        pre_tasks/version_check.yml
    - name: Collect facts except Ohai
      setup:
        gather_subset: "!ohai"
  roles:
    - common

- name: common settings for windows hosts
  hosts: windows
  roles:
    - win
