- block:
# name: Setting up apt repositories for Debian

  - name: Add apt-transport-https package
    apt:
      name: apt-transport-https
      state: present
      update_cache: no

  - name: Add official apt sources.list (https)
    apt_repository:
      repo: '{{ item }}'
      state: present
      filename: stretch
      update_cache: no
    with_items:
      - 'deb https://deb.debian.org/debian stretch main contrib non-free'
      - 'deb-src https://deb.debian.org/debian stretch main contrib non-free'
      - 'deb https://deb.debian.org/debian stretch-updates main contrib non-free'
      - 'deb-src https://deb.debian.org/debian stretch-updates main contrib non-free'
      - 'deb http://security.debian.org/debian-security/ stretch/updates main contrib non-free'
      - 'deb-src http://security.debian.org/debian-security/ stretch/updates main contrib non-free'
    when:
      - "ansible_distribution == 'Debian'"

  - name: Add official backports apt sources.list (https)
    apt_repository:
      repo: '{{ item }}'
      state: present
      filename: stretch-backports
      update_cache: no
    with_items:
      - 'deb https://deb.debian.org/debian stretch-backports main contrib non-free'
      - 'deb-src https://deb.debian.org/debian stretch-backports main contrib non-free'
    when:
      - "ansible_distribution == 'Debian'"

  - name: Add official apt sources.list (http)
    apt_repository:
      repo: '{{ item }}'
      state: present
      filename: bionic
      update_cache: no
    with_items:
      - deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
      - deb-src http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
      - deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe multiverse restricted
      - deb-src http://archive.ubuntu.com/ubuntu/ bionic-updates universe multiverse restricted
      - deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
      - deb-src http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
      - deb http://archive.canonical.com/ubuntu bionic partner
      - deb-src http://archive.canonical.com/ubuntu bionic partner
      - deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
      - deb-src http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
    when:
      - "ansible_distribution == 'Ubuntu'"

  - name: Remove old sources.list file
    file:
      path: /etc/apt/sources.list
      state: absent

  - name: Update apt cache only once in 1h
    apt:
      update_cache: yes
      cache_valid_time: 3600

  become: true
  when:
    - "ansible_os_family == 'Debian'"
