- name: Setting up apt repositories for Debian
  block:

  - name: Add apt-transport-https package
    apt:
      name: apt-transport-https
      state: present
      update_cache: no
    when:
      - "ansible_distribution == 'Debian'"
      - "ansible_distribution_version is search('stretch')"

  - name: Remove apt-transport-https package
    apt:
      name: apt-transport-https
      state: absent
      update_cache: no
    when:
      - "ansible_distribution == 'Debian'"
      - "ansible_distribution_version is not search('stretch')"

  - name: Add official apt sources.list (https) (Debian)
    apt_repository:
      repo: '{{ item }}'
      state: present
      filename: '{{ ansible_lsb.codename }}'
      update_cache: no
    with_items:
      - 'deb https://deb.debian.org/debian {{ ansible_lsb.codename }} main contrib non-free'
      - 'deb-src https://deb.debian.org/debian {{ ansible_lsb.codename }} main contrib non-free'
      - 'deb https://deb.debian.org/debian {{ ansible_lsb.codename }}-updates main contrib non-free'
      - 'deb-src https://deb.debian.org/debian {{ ansible_lsb.codename }}-updates main contrib non-free'
      - 'deb http://security.debian.org/debian-security/ {{ ansible_lsb.codename }}/updates main contrib non-free'
      - 'deb-src http://security.debian.org/debian-security/ {{ ansible_lsb.codename }}/updates main contrib non-free'
    when:
      - "ansible_distribution == 'Debian'"

  - name: Add official backports apt sources.list (https) (Debian)
    apt_repository:
      repo: '{{ item }}'
      state: present
      filename: '{{ ansible_lsb.codename }}-backports'
      update_cache: no
    with_items:
      - 'deb https://deb.debian.org/debian {{ ansible_lsb.codename }}-backports main contrib non-free'
      - 'deb-src https://deb.debian.org/debian {{ ansible_lsb.codename }}-backports main contrib non-free'
    when:
      - "ansible_distribution == 'Debian'"
      - "ansible_distribution_version is search('stretch')"

  - name: Add official apt sources.list (http) (Ubuntu)
    apt_repository:
      repo: '{{ item }}'
      state: present
      filename: '{{ ansible_lsb.codename }}'
      update_cache: no
    with_items:
      - "deb http://archive.ubuntu.com/ubuntu {{ ansible_lsb.codename }} main restricted universe multiverse"
      - "deb-src http://archive.ubuntu.com/ubuntu {{ ansible_lsb.codename }} main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates universe multiverse restricted"
      - "deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates universe multiverse restricted"
      - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-backports main restricted universe multiverse"
      - "deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-backports main restricted universe multiverse"
      - "deb http://archive.canonical.com/ubuntu {{ ansible_lsb.codename }} partner"
      - "deb-src http://archive.canonical.com/ubuntu {{ ansible_lsb.codename }} partner"
      - "deb http://security.ubuntu.com/ubuntu {{ ansible_lsb.codename }}-security main restricted universe multiverse"
      - "deb-src http://security.ubuntu.com/ubuntu {{ ansible_lsb.codename }}-security main restricted universe multiverse"
    when:
      - "ansible_distribution == 'Ubuntu'"

  - name: Remove old sources.list file
    file:
      path: /etc/apt/sources.list
      state: absent

  - name: Update apt cache only once in 1h
    apt:
      update_cache: yes
      cache_valid_time: 3600

  become: true
  when:
    - "ansible_os_family == 'Debian'"

- name: Package preparation on Debian GNU/Linux based distribution
  block:

  - name: install common packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - aptitude
      - apt-listchanges
      #- apt-listbugs
      - host
      - iputils-ping
      - psmisc
      - git
      - locales
      - openssh-client
      - rsync
      - gpg-agent
      - htop
      - strace
      - lsof
      - mlocate

  - name: install ansible related packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - ansible
      - ansible-doc
      - ansible-lint
    when:
      - "ansible_kernel is match('.*Microsoft$')"

  - name: install vim
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - vim

  - name: uninstall vim-tiny
    apt:
      name: "{{ packages }}"
      state: absent
      purge: yes
    vars:
      packages:
      - vim-tiny

  - name: install emacs (on buster and sid)
    apt:
      name: "{{ packages }}"
      state: latest
      install_recommends: yes
    vars:
      packages:
      - emacs
    when:
      - "ansible_distribution == 'Debian'"
      - "ansible_distribution_version is search('buster|sid')"

  - name: install emacs25 (on stretch)
    apt:
      name: "{{ packages }}"
      state: latest
      install_recommends: yes
    vars:
      packages:
      - emacs25
    when:
      - "ansible_distribution == 'Debian'"
      - "ansible_distribution_version is search('stretch')"

  - name: install emacs (on Ubuntu)
    apt:
      name: "{{ packages }}"
      state: latest
      install_recommends: yes
    vars:
      packages:
      - emacs25
    when:
      - "ansible_distribution == 'Ubuntu'"

  - name: install msmtp and mutt
    apt:
      name: '{{ packages }}'
      state: latest
    vars:
      packages:
      - mutt
      - msmtp
    become: true

  - name: install reportbug
    apt:
      name: "{{ packages }}"
      state: latest
      install_recommends: yes
    vars:
      packages:
      - reportbug
    when:
      - "ansible_distribution == 'Debian'"

  - name: change /etc/locale.gen properly
    lineinfile:
      dest: /etc/locale.gen
      regexp: "^# {{ item }}"
      line:   "{{ item }}"
      state: present
      backrefs: yes
    with_items:
      - ja_JP.UTF-8 UTF-8
      - en_US.UTF-8 UTF-8
    notify:
      - rebuild locales database
    when:
      - "ansible_distribution == 'Debian'"

  become: true
  when:
    - "ansible_os_family == 'Debian'"
