- name: Install latest TeXLive
  block:

  - name: Install TeXLive packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - texlive
      - texlive-latex-base-doc
      - texlive-latex-recommended-doc
      - texlive-fonts-recommended-doc
      - texlive-lang-japanese
      - texlive-publishers
      - texlive-publishers-doc
      - lmodern
      - auctex

  become: true
