- name: Install packages by Chocolatey
  win_chocolatey:
    name: '{{ packages }}'
    state: latest
  vars:
    packages:
    - 7zip
    - firefox
    #- googlechrome
    - sysinternals
    - google-backup-and-sync
    - vcxsrv
    #- gpg4win
    #- keepass
    #- keepassxc
    #- bitwarden
    - vscode
    - office365business

- name: Enable Windows Sandbox
  win_command: powershell.exe -
  args:
    stdin: Enable-WindowsOptionalFeature -FeatureName Containers-DisposableClientVM -Online -All
