- name: rebuild locales database
  become: true
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure locales -f noninteractive
    - /usr/sbin/locale-gen
  when:
    - "ansible_distribution == 'Debian'"
