- block:

  - name: install machine learning packages
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - jupyter-notebook
      - python3-sklearn
      - python3-matplotlib
    when:
      - "ansible_distribution == 'Debian'"

  become: true
