- block:

  - name: install common packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - man-db
      - git-doc
      - manpages-dev
      - build-essential
      - make-doc
      - libstdc++-6-doc
      - gcc-doc
      - cpp-doc
      - glibc-doc
      - gdb
      - gdb-doc

  - name: install emacs25 packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - lookup-el
      - migemo-el
      - elpa-magit
      - aspell
      - aspell-en
      - aspell-doc

  - name: install python3 packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - python3-doc
      - flake8
      - pylama

  - name: install machine learning packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - jupyter-notebook
      - python3-sklearn
      - python3-matplotlib
      - python-numpy-doc
      - python-scipy-doc
      - python-sklearn-doc
      - python-matplotlib-doc
  - name: install c++ packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - clang
      - clang-format
      - clang-tidy
      - iwyu
      - libboost-dev
      - libboost-doc

  become: true
  when:
    - "ansible_distribution == 'Debian'"
