- block:
# name: Setting up packages for Debian

  - name: install common packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - man-db
      - git-doc
      - build-essential
      - manpages-dev
#      - make-doc
#      - libstdc++-6-doc
#      - gcc-doc
#      - cpp-doc
#      - glibc-doc
      - gdb
#      - gdb-doc

  - name: install emacs25 packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - lookup-el
      - migemo-el
      - elpa-magit
      - aspell
      - aspell-en
      - aspell-doc
      - global

  - name: install python3 packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - python3
      - python3-doc
      - flake8
      - pylama
      - yapf3

  - name: install machine learning packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - jupyter-notebook
      - python3-sklearn
      - python3-matplotlib
      - python-numpy-doc
      - python-scipy-doc
      - python-sklearn-doc
      - python-matplotlib-doc

  - name: install c++ packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - clang
      - clang-format
      - clang-tidy
      - iwyu
      - libboost-dev
      - libboost-doc

  - name: install performance analysis packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - linux-perf

  become: true
  when:
    - "ansible_distribution == 'Debian'"
