- name: Setting up packages for Debian
  block:

  - name: install common packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - build-essential
      - gdb
      - lldb

  - name: install documentation packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - man-db
      - git-doc
      - manpages-dev
      - make-doc
#      - gcc-doc
#      - cpp-doc
      - glibc-doc
      - gdb-doc

  - name: install libstdc++ documentation package (buster/sid)
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - libstdc++-8-doc
    when:
      - "ansible_distribution_release is search('buster|sid')"

  - name: install emacs packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - lookup-el
      - elpa-migemo
      - elpa-magit
      - elpa-yaml-mode
      - elpa-company
      - elpa-counsel
      - elpa-lsp-ui
      - aspell
      - aspell-en
      - aspell-doc
      - global

  - name: install python3 packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - python3
      - python3-doc
      - black
      - flake8
      - python3-flake8-docstrings

  - name: install machine learning packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - jupyter
      - python3-sklearn
      - python3-pandas
      - python3-xlrd
      - python3-matplotlib
      - python-numpy-doc
      - python-scipy-doc
      - python-sklearn-doc
      - python-matplotlib-doc
      - python-pandas-doc

  - name: install c++ packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - clang
      - clang-format
      - clang-tidy
      - clang-tools
      - iwyu
      - libboost-dev
      - libboost-doc

  - name: install performance analysis packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - linux-perf
    when:
      "ansible_kernel is not match('.*Microsoft$')"

  - name: install Julia package (buster/sid)
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - julia
      - julia-doc
    notify:
      - add Julia packages
    when:
      - "ansible_distribution_version is search('buster|sid')"

  become: true
  when:
    - "ansible_distribution == 'Debian'"
