- name: Setting up packages for Debian
  block:

  - name: install common packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - build-essential
      - gdb

  - name: install documentation packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - man-db
      - git-doc
      - manpages-dev
      - make-doc
#      - gcc-doc
#      - cpp-doc
      - glibc-doc
      - gdb-doc

  - name: install libstdc++ documentation package (buster)
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - libstdc++-8-doc
    when:
      - "ansible_distribution_version is search('buster')"

  - name: install emacs packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - lookup-el
      - elpa-migemo
      - elpa-magit
      - elpa-yaml-mode
      - aspell
      - aspell-en
      - aspell-doc
      - global

  - name: install python3 packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - python3
      - python3-doc
      - flake8
      - pylama
      - yapf3

  - name: install machine learning packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - jupyter
      - python3-sklearn
      - python3-matplotlib
      - python-numpy-doc
      - python-scipy-doc
      - python-sklearn-doc
      - python-matplotlib-doc

  - name: install c++ packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - clang
      - clang-format
      - clang-tidy
      - iwyu
      - libboost-dev
      - libboost-doc

  - name: install performance analysis packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - linux-perf
    when:
      "ansible_kernel is not match('.*Microsoft$')"

  - name: install julia package (buster)
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - julia
      - julia-doc
    when:
      - "ansible_distribution_version is search('buster')"

  become: true
  when:
    - "ansible_distribution == 'Debian'"
