- block:
# name: tmux settings

  - name: install tmux
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - tmux
    become: true

  - name: create symlinks of tmux configuration files
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/{{ item }}'
      dest: '{{ ansible_env.HOME }}/{{ item }}'
      state: link
    with_items:
      - .tmux.conf
    become: false

  - name: prepare Windows fonts directory for WSL
    file:
      path: '{{ ansible_env.HOME }}/.local/share/fonts'
      state: directory
      force: true
    become: false

  - name: use Windows fonts on WSL
    file:
      src:  /mnt/c/Windows/Fonts
      dest: '{{ ansible_env.HOME }}/.local/share/fonts/win'
      state: link
    notify:
      - run fc-cache
    become: false

  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"
