- name: tmux settings
  block:

  - name: install tmux
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - tmux
    become: true

  - name: create symlinks of tmux configuration files
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/{{ item }}'
      dest: '{{ ansible_env.HOME }}/{{ item }}'
      state: link
    with_items:
      - .tmux.conf
    become: false

  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"

- name: font settings
  block:

  - name: prepare Windows fonts directory for WSL
    file:
      path: '{{ ansible_env.HOME }}/.local/share/fonts'
      state: directory
      force: true
    become: false

  - name: use Windows fonts on WSL
    file:
      src:  /mnt/c/Windows/Fonts
      dest: '{{ ansible_env.HOME }}/.local/share/fonts/win'
      state: link
    notify:
      - run fc-cache
    become: false

  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"

- name: GnuPG settings
  block:

  - name: install GnuPG management packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - gpg-agent
      - pinentry-qt
      - dirmngr

  - name: make sure that pinentry-* other than qt are uninstalled
    apt:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - pinentry-tty
      - pinentry-curses
      - pinentry-gnome3
      - pinentry-gtk2
      - pinentry-fltk
      - pinentry-qt4

  - name: create symlinks of gpg related script files
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/bin/{{ item }}'
      dest: '{{ ansible_env.HOME }}/bin/{{ item}}'
      state: link
    with_items:
      - remote-gpg

  - name: point IdentityAgent to gpg-agent
    lineinfile:
      dest: '{{ ansible_env.HOME }}/.ssh/config'
      regexp: '^\s*IdentityAgent'
      line: '  IdentityAgent {{ sshsocket }}'
      state: present

  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"
