- name: /etc/wsl.conf settings
  block:

  - name: create /etc/wsl.conf on wsl machine
    template:
      src: wsl.conf.j2
      dest: /etc/wsl.conf
      owner: root
      mode: '0644'
    become: true

  when:
    - "ansible_kernel is match('.*Microsoft$')"

- name: Google Cloud Platform settings
  block:

  - name: Add Google Cloud Platform repository
    apt_repository:
      repo: 'deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main'
      state: present
      filename: 'gcp'
      update_cache: no

  - name: Add Google Cloud Platform repository key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name : Install Google Cloud Platform SDK
    apt:
      name: google-cloud-sdk
      state: latest
      update_cache: true

  become: true

- name: tmux settings
  block:

  - name: install tmux
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - tmux
    become: true

  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"

- name: font settings
  block:

  - name: prepare Windows fonts directory for WSL
    file:
      path: '{{ ansible_env.HOME }}/.local/share/fonts'
      state: directory
      force: true
    become: false

  - name: use Windows fonts on WSL
    file:
      src:  /mnt/c/Windows/Fonts
      dest: '{{ ansible_env.HOME }}/.local/share/fonts/win'
      state: link
    notify:
      - run fc-cache
    become: false

  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"

- name: GnuPG settings
  block:

  - name: install GnuPG management packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - gnupg
      - pinentry-qt
      - dirmngr
    become: True

  - name: make sure that pinentry-* other than qt are uninstalled
    apt:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - pinentry-tty
      - pinentry-curses
      - pinentry-gnome3
      - pinentry-gtk2
      - pinentry-fltk
      - pinentry-qt4
    become: True

  - name: make sure that $HOME/bin directory is present
    file:
      path: '{{ ansible_env.HOME }}/bin'
      state: directory

  - name: create symlinks of gpg related script files
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/bin/{{ item }}'
      dest: '{{ ansible_env.HOME }}/bin/{{ item }}'
      state: link
    with_items:
      - remote-gpg

  - name: point IdentityAgent to gpg-agent
    lineinfile:
      dest: '{{ ansible_env.HOME }}/.ssh/config'
      regexp: '^\s*IdentityAgent'
      line: '  IdentityAgent {{ sshsocket }}'
      state: present

  become: false
  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"

- name: Emacs settings
  block:

  - name: symlink EPWING folder
    file:
      src:  '{{ ansible_env.HOME }}/win/OneDrive/EPWING'
      dest: '{{ ansible_env.HOME }}/EPWING'
      state: link

  become: false
  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"

- name: ansible for windows host settings
  block:

  - name: prepare ConfigureRemotingForAnsible.ps1
    shell: gunzip --stdout /usr/share/doc/ansible-doc/examples/scripts/ConfigureRemotingForAnsible.ps1.gz > /tmp/ConfigureRemotingForAnsible.ps1
    args:
      creates: /tmp/ConfigureRemotingForAnsible.ps1

  - name: prepare winrm settings
    command: powershell.exe -Command "Start-Process powershell.exe -Verb runAs -ArgumentList \"-ExecutionPolicy RemoteSigned\", '\\\\wsl\`$\\Debian\\tmp\\ConfigureRemotingForAnsible.ps1', \"-EnableCredSSP\", \"-DisableBasicAuth\", \"-SkipNetworkProfileCheck\""

  - name: install needed package for credssp
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - gcc
      - python3-dev
      - libssl-dev
    become: true

  - name: prepare credssp enable pywinrm via pip
    pip:
      name: pywinrm[credssp]
      executable: pip3

  become: false
  when:
    - "ansible_kernel is match('.*Microsoft$')"
    - "ansible_os_family == 'Debian'"
