- name: Setting dotfiles
  block:

  - name: clone dotfiles from github
    git:
      repo: 'ssh://git@github.com/rigarash/dotfiles.git'
      dest: '{{ ansible_env.HOME }}/.dotfiles'
      update: yes
      accept_hostkey: yes

  - name: move original various configuration files
    stat:
      path: '{{ ansible_env.HOME }}/{{ item }}'
    with_items:
      - .gitconfig
      - .dircolors
      - .python_startup
      - .zsh.d
      - .zshrc
    register: conffiles

  - name: move original various configuration files
    command: mv '{{ ansible_env.HOME }}/{{ item.item }}' '{{ ansible_env.HOME }}/{{ item.item }}.orig'
    args:
      creates: '{{ ansible_env.HOME }}/{{ item.item }}.orig'
      removes: '{{ ansible_env.HOME }}/{{ item.item }}'
    when:
      - item.stat is defined
      - item.stat.isreg is defined
      - item.stat.isreg
      - item.stat.islnk is defined
      - item.stat.islnk == False
    with_items:
      - '{{ conffiles.results }}'

  - name: create symlinks of various configuration files 
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/{{ item }}'
      dest: '{{ ansible_env.HOME }}/{{ item }}'
      state: link
    with_items:
      - .gitconfig
      - .dircolors
      - .python_startup
      - .zsh.d
      - .zshrc

  - name: change .gitconfig on RICOS
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/.gitconfig-ricos'
      dest: '{{ ansible_env.HOME }}/.gitconfig'
      state: link
    when:
      - "'ricos' in group_names"

  - name: change shell to zsh
    user:
      name: rigarash
      shell: /bin/zsh
    when:
      - "ansible_os_family == 'Debian'"

  - name: create folders for emacs
    file:
      path: '{{ ansible_env.HOME }}/.emacs.d'
      state: directory

  - name: create symlinks for emacs
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/.emacs.d/{{ item }}'
      dest: '{{ ansible_env.HOME }}/.emacs.d/{{ item }}'
      state: link
    with_items:
      - init.el

  become: false

- name: Setting for openssh
  block:

  - name: create socket folders for openssh
    file:
      path:  '{{ ansible_env.HOME }}/.ssh/socket'
      state: directory

  - name: create symlink to openssh config file
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/.ssh/{{ item }}'
      dest: '{{ ansible_env.HOME }}/.ssh/{{ item }}'
      state: link
    with_items:
      - config

  - name: check whether current authorized_keys is symlink
    stat:
      path: '{{ ansible_env.HOME }}/.ssh/authorized_keys'
    register: ssh_keys

  - name: remove current authorized_keys when symlink
    file:
      path: '{{ ansible_env.HOME }}/.ssh/authorized_keys'
      state: absent
      follow: no
    when:
      - ssh_keys.stat.islnk is defined
      - ssh_keys.stat.islnk
      - ssh_keys.stat.lnk_source is not search('\.dotfiles')

  - name: create symlink to openssh authorized_keys
    file:
      src:  '{{ ansible_env.HOME }}/.dotfiles/.ssh/{{ item }}'
      dest: '{{ ansible_env.HOME }}/.ssh/{{ item }}'
      state: link
    with_items:
      - authorized_keys

  - name: check openssh private keys
    stat:
      path: '{{ ansible_env.HOME }}/.ssh/{{ item }}'
    register: private_keys
    with_items:
      - id_rsa
      - id_rsa_v2
      - id_ecdsa

  - name: remove wrong openssh private keys
    file:
      path: '{{ item.stat.path }}'
      state: absent
      follow: no
    when:
      - item.stat.islnk is defined
      - item.stat.islnk
      - item.stat.lnk_source is not search( ansible_env.USERPROFILE + '/home/ssh_private/' + item.item )
    with_items:
      - '{{ private_keys.results }}'

  - name: setting up symlinks of openssh private keys
    file:
      src:  '{{ ansible_env.USERPROFILE }}/home/ssh_private/{{ item.item }}'
      dest: '{{ item.stat.path }}'
      state: link
    when:
      - item.stat.path is defined
    with_items:
      - '{{ private_keys.results }}'

  - name: fixing mode of .ssh/config
    file:
      path: '{{ ansible_env.HOME }}/.ssh/config'
      mode: '600'
      follow: yes

  become: false
