- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when:
    - "ansible_os_family == 'Debian'"

- name: install common packages
  become: true
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - man-db
    - manpages-dev
    - make
    - host
    - iputils-ping
  when:
    - "ansible_distribution == 'Debian'"

- name: install vim
  become: true
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - vim
  when:
    - "ansible_distribution == 'Debian'"

- name: uninstall vim-tiny
  become: true
  apt:
    name: "{{item}}"
    state: absent
  with_items:
    - vim-tiny
  when:
    - "ansible_distribution == 'Debian'"
