- name: install common packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - aptitude
    - man-db
    - manpages-dev
    - host
    - iputils-ping
    - make
    - git
  when:
    - "ansible_distribution == 'Debian'"

- name: install vim
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - vim
  when:
    - "ansible_distribution == 'Debian'"

- name: uninstall vim-tiny
  apt:
    name: "{{item}}"
    state: absent
    purge: yes
  with_items:
    - vim-tiny
  when:
    - "ansible_distribution == 'Debian'"

- name: install emacs25
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - emacs25
    - lookup-el
    - migemo-el
    - elpa-magit
  when:
    - "ansible_distribution == 'Debian'"

- name: change /etc/locale.gen properly
  lineinfile:
    dest: /etc/locale.gen
    regexp: "^# {{item}}"
    line:   "{{item}}"
    state: present 
    backrefs: yes
  with_items:
    - ja_JP.UTF-8 UTF-8
    - en_US.UTF-8 UTF-8
  notify:
    - rebuild locales database
  when:
    - "ansible_distribution == 'Debian'"

- block:

  - name: clone dotfiles from github
    git:
      repo: 'ssh://git@github.com/rigarash/dotfiles.git'
      dest: "{{ ansible_env.HOME }}/.dotfiles"
      accept_hostkey: yes

  - name: create symlinks of various configuration files 
    file:
      src:  '{{ ansible_env.HOME}}/.dotfiles/{{ item }}'
      dest: '{{ ansible_env.HOME}}/{{ item }}'
      state: link
    with_items:
      - .gitconfig
      - .dircolors
      - .zsh.d
      - .zshrc

  - name: create symlinks to openssh related files
    file:
      src:  '{{ ansible_env.HOME}}/.dotfiles/.ssh/{{ item }}'
      dest: '{{ ansible_env.HOME}}/.ssh/{{ item }}'
      state: link
    with_items:
       - authorized_keys
       - config

  become: false
